# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0c79952dbb8e646f9d5bd3b02f833de43beb875e001f517fa6056aef30ee31be78109c3af8345b1be8c1b3ec0a5ffd674ef111a5c1e5673465c51d06d62c348

test:
  secret_key_base: e98bff1440b3ad960be020c630f8486386dc49479b8f2baf7de3615f79f6e7b0a1184c29f0d0ba5c6f4d8bbc66ece555dd9970304c4202b31fa7b8b3d59c7ac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
